/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    Avatar: typeof import('primevue/avatar')['default']
    AvatarGroup: typeof import('primevue/avatargroup')['default']
    BBSView: typeof import('./src/components/BBSView.vue')['default']
    Button: typeof import('primevue/button')['default']
    Card: typeof import('primevue/card')['default']
    ContentView: typeof import('./src/components/ContentView.vue')['default']
    Fieldset: typeof import('primevue/fieldset')['default']
    Homecontent: typeof import('./src/components/Homearea/Homecontent.vue')['default']
    Hometop: typeof import('./src/components/Hometop.vue')['default']
    Navigation: typeof import('./src/components/Navigation.vue')['default']
    PaddleCard: typeof import('./src/components/Homearea/PaddleCard.vue')['default']
    ProductIntroduction: typeof import('./src/components/Homearea/ProductIntroduction.vue')['default']
    ProgressBar: typeof import('primevue/progressbar')['default']
    RankingView: typeof import('./src/components/RankingView.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Skeleton: typeof import('./src/components/SkeletonComponent/Skeleton.vue')['default']
    Tab: typeof import('primevue/tab')['default']
    TabList: typeof import('primevue/tablist')['default']
    Tabs: typeof import('primevue/tabs')['default']
    TieredMenu: typeof import('primevue/tieredmenu')['default']
    Toggleswitch: typeof import('./src/components/toggleswitch.vue')['default']
    VirtualScroller: typeof import('primevue/virtualscroller')['default']
  }
  export interface GlobalDirectives {
    Ripple: typeof import('primevue/ripple')['default']
  }
}
