/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AvatarGroup: typeof import('primevue/avatargroup')['default']
    Button: typeof import('primevue/button')['default']
    FileUpload: typeof import('primevue/fileupload')['default']
    Home: typeof import('./src/components/Home.vue')['default']
    Homecontent: typeof import('./src/components/Homearea/Homecontent.vue')['default']
    Hometop: typeof import('./src/components/Homearea/Hometop.vue')['default']
    Messages: typeof import('./src/components/Messages.vue')['default']
    Navigation: typeof import('./src/components/Navigation.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Toast: typeof import('primevue/toast')['default']
  }
}
