/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    Ada: typeof import('./src/components/Homearea/ada.vue')['default']
    Avatar: typeof import('primevue/avatar')['default']
    AvatarGroup: typeof import('primevue/avatargroup')['default']
    BBSView: typeof import('./src/components/BBSView.vue')['default']
    Button: typeof import('primevue/button')['default']
    Card: typeof import('primevue/card')['default']
    Chip: typeof import('primevue/chip')['default']
    Commentsection: typeof import('./src/components/Commentsection/index.vue')['default']
    ContentView: typeof import('./src/components/ContentView.vue')['default']
    copy: typeof import('./src/components/Homearea/Homecontent copy.vue')['default']
    Divider: typeof import('primevue/divider')['default']
    Drawer: typeof import('primevue/drawer')['default']
    Fieldset: typeof import('primevue/fieldset')['default']
    Homecontent: typeof import('./src/components/Homearea/Homecontent.vue')['default']
    'Homecontent copy': typeof import('./src/components/Homearea/Homecontent copy.vue')['default']
    Hometop: typeof import('./src/components/Hometop.vue')['default']
    Image: typeof import('primevue/image')['default']
    Navigation: typeof import('./src/components/Navigation.vue')['default']
    PaddleCard: typeof import('./src/components/Homearea/PaddleCard.vue')['default']
    Panel: typeof import('primevue/panel')['default']
    ProductIntroduction: typeof import('./src/components/Homearea/ProductIntroduction.vue')['default']
    ProgressBar: typeof import('primevue/progressbar')['default']
    ProgressSpinner: typeof import('primevue/progressspinner')['default']
    RankingView: typeof import('./src/components/RankingView.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    ScrollPanel: typeof import('primevue/scrollpanel')['default']
    Sidebar: typeof import('primevue/sidebar')['default']
    Skeleton: typeof import('./src/components/SkeletonComponent/Skeleton.vue')['default']
    Tab: typeof import('primevue/tab')['default']
    TabList: typeof import('primevue/tablist')['default']
    Tabs: typeof import('primevue/tabs')['default']
    TieredMenu: typeof import('primevue/tieredmenu')['default']
    Toggleswitch: typeof import('./src/components/toggleswitch.vue')['default']
    VirtualScroller: typeof import('primevue/virtualscroller')['default']
  }
  export interface GlobalDirectives {
    Ripple: typeof import('primevue/ripple')['default']
    StyleClass: typeof import('primevue/styleclass')['default']
  }
}
